import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { JSX } from "react";
import {
  BookOpen,
  Boxes,
  Brain,
  ChevronRight,
  Download,
  FileText,
  Maximize2,
  MessageSquare,
  Pause,
  Pencil,
  Play,
  RefreshCw,
  RotateCcw,
  Sparkles,
  X,
} from "lucide-react";
import {
  CONNECTOME_PERSONAS,
  COUPLING_HOW,
  COUPLING_LABELS,
  DEFAULT_CONNECTOME_WEIGHTS,
  IQ_CELL_ORIGIN_LABELS,
  MYIQ_DEFAULT_NAME,
  ORIGIN_LABELS,
  ConnectomePersona,
  type ConnectomeBundle,
  type ConnectomeEdge,
  type ConnectomeFinding,
  type ConnectomeGraph,
  type ConnectomeNode,
  type ConnectomeReport,
  type ConnectomeSelection,
  type CouplingComponent,
  type MyIqPublishResult,
} from "@iq/shared";
import { call } from "../bridge.js";
import { Modal } from "../Modal.js";
import { generateLibrary, type DemoIqCell } from "./fixtures.js";
import { industryCells } from "../industry/cells.js";
import { analyzeStaged, buildReport, ANALYSIS_STAGES, LATENT_FLOOR, type AnalysisStage } from "./analyze.js";
import { draftFromCell } from "./draft.js";
import { ConnectomeChat } from "./Chat.js";
import { ConnectomeScene, webglAvailable } from "./scene.js";
import { useTimeLapse } from "./timelapse.js";
import { stageForEditor } from "../flow/storage.js";
import { device } from "../flow/device.js";
import { routeForCell, type IqCellRoute } from "../flow/route.js";
import { stepLabel, useStepProgress } from "../flow/useStepProgress.js";
import { SplitDivider, useSplit, type ColumnSpec } from "../split.js";

/**
 * How long after a publish the MCP dialog appears.
 *
 * Long enough that it reads as a second, separate result rather than as part
 * of the publish that just finished, and short enough that it is still
 * obviously a consequence of the button.
 */
const PUBLISH_DIALOG_DELAY_MS = 2_500;

/** Where the edited build instructions are kept. */
const INSTRUCTIONS_KEY = "iq.myiq.instructions";

/**
 * How My IQ gets built, in the order it happens.
 *
 * People arrive at this surface and see a graph with no account of where it
 * came from, which makes the map something to be taken on trust — the one
 * thing this analysis is not meant to be. So the recipe is written down, and
 * it is written down as text the reader can change: the default describes what
 * the app does today, and someone whose material or intent is different should
 * be able to say so and keep it.
 *
 * The signal names match `COUPLING_HOW` in the shared contract. If the
 * analysis changes what it compares, this text is wrong and has to move with
 * it.
 */
const DEFAULT_INSTRUCTIONS = `My IQ is compiled, not written. It is built from the IQ Cells you already have.

1. Choose the material. The IQ Cells panel lists every compiled cell — from IQ Industry, IQ Workflow, IQ Memories and the IQ Cell library. Only the ones ticked are read. Nothing else is.

2. Compare every pair. Each selected pair is scored on six signals, all of them declarations the cells already carry:
   - Artifact lineage — one writes a file the other reads.
   - Shared project reach — both declare the same project paths.
   - Shared external reach — both hold the same outside grant.
   - Shared configuration — both name the same model, skill, MCP server or connection.
   - Temporal co-activation — their runs land in the same hours.
   - Same approver — the same person approves both.

3. Draw the result. Cells become nodes, strong pairs become edges. The graph hash in the header is the fingerprint of the selection, so the same cells always give the same map.

4. Read the report. It names what the analysis found, how strong each finding is, and what it cannot see. No model is asked at any point — the chat answers from this analysis alone.

5. Publish. Naming it writes a read-only MCP server that serves this library and this analysis. Other apps, and Connectome IQ, read it through five tools.

Edit this to describe how your own My IQ should be built. It is kept on this device.`;

/**
 * IQ Cell → My IQ (beta).
 *
 * The parent layer: not what one IQ Cell does, but what the whole body of work
 * looks like. This is a reading surface — nothing on it executes, no edge is
 * drawn by hand, and the map is rendered deterministically by the renderer
 * from the analysis rather than generated by a model.
 *
 * The beta runs the analysis over a seeded demo library, which is stated on
 * the surface and in the report's limits section rather than implied.
 */

const WEIGHT_KEYS = Object.keys(DEFAULT_CONNECTOME_WEIGHTS) as CouplingComponent[];

type ConnectomeView = "map" | "table";

const VIEW_LABELS: Record<ConnectomeView, string> = {
  map: "Map",
  table: "Table",
};

const VIEW_HINTS: Record<ConnectomeView, string> = {
  map: "The whole selection as one image — shape first, detail second.",
  table: "Every connection as a row, sorted by strength.",
};

interface ConnectomeProps {
  projectId: string | null;
  onError: (problem: unknown) => void;
  /**
   * Take the reader where the cell came from.
   *
   * One callback rather than one per origin: `routeForCell` decides where a
   * cell belongs, so this surface and the IQ Cell library cannot answer that
   * question differently — which they did, for as long as each held its own
   * switch.
   */
  onOpenCell: (route: IqCellRoute) => void;
}

/**
 * The selection list holds names the user wrote, so no fixed width is right
 * for everyone. It starts closed because the map is the opening view; when a
 * reader asks to select cells, it opens wide enough for realistic names and is
 * draggable from there.
 *
 * The right-hand column is declared separately because it is not always there.
 * `useSplit` derives its grid template from the specs it is handed, so leaving
 * the entry out is what closes the column — no collapse state inside the hook,
 * and no zero-width column pretending to be absent.
 */
const CONNECTOME_COLUMNS: Partial<Record<"list" | "report", ColumnSpec>> = {
  list: { min: 220, initial: 320, side: "left" },
};

const REPORT_COLUMN: Partial<Record<"list" | "report", ColumnSpec>> = {
  report: { min: 260, initial: 340, side: "right" },
};

export function Connectome({
  projectId,
  onError,
  onOpenCell,
}: ConnectomeProps): JSX.Element {
  /**
   * The whole body of work, not only the seeded part.
   *
   * The industry primers are added alongside the demo library rather than
   * generated into it: they ship with the app, so they are here whether or not
   * the worked examples are wanted, and a map that left out the domain briefs
   * the rest of the work is grounded on would be missing the layer underneath
   * everything else.
   */
  const library = useMemo<DemoIqCell[]>(() => [...industryCells(), ...generateLibrary()], []);
  const [chosen, setChosen] = useState<string[]>(() => library.map((row) => row.id));
  const [windowDays, setWindowDays] = useState(30);
  const [weights, setWeights] =
    useState<Record<CouplingComponent, number>>(DEFAULT_CONNECTOME_WEIGHTS);
  /**
   * Who the findings are ordered for.
   *
   * Held apart from the run, and deliberately outside the graph hash. The same
   * body of work is a different problem to a budget owner and to a security
   * reviewer, but it is the same body of work: changing the reader must not
   * move a single node on the map, and must not cost a second analysis.
   */
  const [persona, setPersona] = useState<ConnectomePersona>("all");
  const lens = CONNECTOME_PERSONAS[persona];
  /**
   * What the last run produced, before any reading is applied to it.
   *
   * The raw findings are kept rather than the built report, because the report
   * is a reading of them. Re-ordering an already-ordered list would make the
   * result depend on which personas had been looked at on the way here.
   */
  const [run, setRun] = useState<{
    selection: ConnectomeSelection;
    graph: ConnectomeGraph;
    findings: ConnectomeFinding[];
  } | null>(null);
  const report = useMemo<ConnectomeReport | null>(
    () =>
      run === null
        ? null
        : buildReport({ ...run.selection, persona }, run.graph, run.findings),
    [persona, run],
  );
  /**
   * The result of the last publish, and whether its dialog is showing.
   *
   * Two pieces of state rather than one, because the dialog appears on a delay:
   * the publish itself has already been reported by the notice, and this is the
   * separate, later message about the MCP server being reachable. Keeping the
   * result once the dialog closes is what lets the MCP surface and a re-open
   * show the same snippet without re-publishing.
   */
  const [published, setPublished] = useState<MyIqPublishResult | null>(null);
  const [showPublished, setShowPublished] = useState(false);
  const [busy, setBusy] = useState(false);
  const [selectedNode, setSelectedNode] = useState<string | null>(null);
  const [selectedEdge, setSelectedEdge] = useState<string | null>(null);
  /**
   * The IQ Cell whose details dialog is open.
   *
   * A node on the map is a blob: it carries size, colour and position, and
   * nothing a reader can name. Selecting one already moved the report pane, but
   * that pane is three columns away and can be hidden, so on the map itself a
   * node stayed anonymous. Opening a dialog over the picked node is what turns
   * it back into a piece of work with an owner, a reach and a set of files.
   *
   * It is kept apart from `selectedNode` on purpose: the guided tour drives the
   * selection, and a dialog that opened itself every few seconds during the
   * tour would be a popup, not an answer to a click.
   */
  const [detailId, setDetailId] = useState<string | null>(null);
  // Lazy, not a bare call: `useState(f())` evaluates `f` on every render, and
  // this one used to open a WebGL context each time.
  const [view, setView] = useState<ConnectomeView>(() => (webglAvailable() ? "map" : "table"));

  /**
   * Motion is opt-in.
   *
   * The map used to start growing, drifting and firing the moment an analysis
   * finished, which meant the first thing a reader got was a picture that would
   * not hold still long enough to be read. Everything animated is now behind
   * this one control, and the still render carries exactly the same
   * information.
   */
  const [motion, setMotion] = useState(false);
  const reducedMotion = useMemo(
    () => window.matchMedia("(prefers-reduced-motion: reduce)").matches,
    [],
  );

  /**
   * What the right-hand column is showing, and whether it is there at all.
   *
   * Chat shares that column rather than adding a fourth: the pane-sizing rules
   * are the one thing on this surface that has to stay simple, and a reader
   * asking the map a question is not also reading the report at that moment.
   *
   * **Closed on arrival.** The map is the reason to be here and it is the
   * elastic column, so 340px of prose beside it was 340px taken from the only
   * thing this surface exists to show — in a 1280px window, with the IQ Cell
   * list on the other side, the picture was getting less than half the pane.
   * The report is also empty until an analysis has been run, so what it cost
   * the map it spent on an empty state. Both openers are in the header and one
   * click brings it back.
   */
  const [rightPane, setRightPane] = useState<"report" | "chat">("report");
  const [rightOpen, setRightOpen] = useState(false);
  const [listOpen, setListOpen] = useState(false);
  const splitColumns = useMemo<Partial<Record<"list" | "report", ColumnSpec>>>(
    () => ({
      ...(listOpen ? CONNECTOME_COLUMNS : {}),
      ...(rightOpen ? REPORT_COLUMN : {}),
    }),
    [listOpen, rightOpen],
  );
  const split = useSplit<"list" | "report">(
    "connectome",
    projectId ?? "none",
    splitColumns,
    360,
  );

  /**
   * How far through a run we are.
   *
   * Null when nothing is running. The reading is taken from the analysis
   * itself — pairs compared, then each later phase as it completes — rather
   * than from a timer, because a bar that advances on its own while the work
   * happens in one blocking call is a decoration, and this is a surface whose
   * whole claim is that its numbers can be checked.
   */
  const [progress, setProgress] = useState<{ stage: AnalysisStage; percent: number } | null>(null);

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const labelsRef = useRef<HTMLDivElement | null>(null);
  const mapRef = useRef<HTMLDivElement | null>(null);
  const sceneRef = useRef<ConnectomeScene | null>(null);
  // Held in a ref because the scene's callbacks are bound once, on mount, and
  // must not be rebuilt every time the time lapse's state changes.
  const pauseRef = useRef<() => void>(() => {});
  const epochRef = useRef<(epoch: number) => void>(() => {});
  /**
   * Start the time lapse.
   *
   * A ref for a different reason than the two above: the lapse is declared
   * below `neuroimage`, because it reads the graph the run produces. A run has
   * to be able to start the playback without the two becoming mutually
   * dependent.
   */
  const playRef = useRef<() => void>(() => {});

  /**
   * Handing My IQ to the MCP server.
   *
   * The map was the only surface that made something and had nowhere to put
   * it. `notice` is the receipt: a publish that leaves no trace on the surface
   * that ran it is indistinguishable from a button that does nothing.
   */
  const publishing = useStepProgress();
  const [notice, setNotice] = useState<string | null>(null);
  /**
   * Whether the name-and-share dialog is up.
   *
   * Publishing asks two questions before it does anything, so the button opens
   * a dialog rather than acting. Both answers are the publisher's to give: what
   * this IQ is called, and whether it is meant for other people. Neither can be
   * derived from the analysis, and guessing them would put a row in Connectome
   * IQ that nobody chose to put there.
   */
  const [naming, setNaming] = useState(false);

  /**
   * The build instructions, and whether they are showing.
   *
   * Read from the device once and held here, so closing the dialog does not
   * cost a second read and the header button can stay a plain toggle.
   */
  const [instructions, setInstructions] = useState(
    () => device().read(INSTRUCTIONS_KEY) ?? DEFAULT_INSTRUCTIONS,
  );
  const [showInstructions, setShowInstructions] = useState(false);

  const saveInstructions = useCallback((text: string): void => {
    setInstructions(text);
    setShowInstructions(false);
    // The default is not written. Storing it would freeze today's wording into
    // the device, so a later change to how the analysis works would be right in
    // the code and stale on every machine that had ever opened this dialog.
    if (text === DEFAULT_INSTRUCTIONS) device().remove(INSTRUCTIONS_KEY);
    else device().write(INSTRUCTIONS_KEY, text);
  }, []);

  const selection = useMemo<ConnectomeSelection>(
    () => ({ projectId, iqCellIds: chosen, windowDays, weights, persona }),
    [chosen, weights, windowDays, projectId, persona],
  );

  const estimate = useMemo(() => {
    const rows = library.filter((row) => chosen.includes(row.id));
    return {
      nodes: rows.length,
      pairs: (rows.length * Math.max(0, rows.length - 1)) / 2,
      runs: rows.reduce((sum, row) => sum + row.runs, 0),
    };
  }, [chosen, library]);

  /**
   * The scene owns a WebGL context bound to one canvas element.
   *
   * The canvas is therefore mounted for the lifetime of the surface and hidden
   * with CSS when another view is showing — unmounting it on a view switch
   * destroyed the element out from under a live scene, and the scene handle
   * that survived then drew into nothing, which is why the map came back blank
   * and unresponsive after a trip through the table.
   */
  useEffect(() => {
    const canvas = canvasRef.current;
    if (canvas === null || sceneRef.current !== null || !webglAvailable()) return;
    try {
      const scene = new ConnectomeScene(
        canvas,
        {
          onPickNode: (id) => {
            pauseRef.current();
            setSelectedNode(id);
            setSelectedEdge(null);
            setDetailId(id);
          },
          onPickEdge: (id) => {
            pauseRef.current();
            setSelectedEdge(id);
            setSelectedNode(null);
            setDetailId(null);
          },
          onEpoch: (value) => epochRef.current(value),
        },
        labelsRef.current,
      );
      scene.setMotion(false);
      sceneRef.current = scene;
    } catch (problem) {
      onError(problem);
      setView("table");
    }

    const onResize = (): void => sceneRef.current?.resize();
    window.addEventListener("resize", onResize);
    return () => {
      window.removeEventListener("resize", onResize);
    };
  }, [onError]);

  // A hidden canvas has no layout box, so its drawing buffer must be measured
  // again on the way back in or the map returns at the wrong size.
  useEffect(() => {
    if (view !== "map") return;
    const frame = window.requestAnimationFrame(() => sceneRef.current?.resize());
    return () => window.cancelAnimationFrame(frame);
  }, [view]);

  /**
   * The map fills a pane, not the window.
   *
   * Hiding the list column or dragging the report pane changes the canvas's box
   * without ever firing a window resize, so the drawing buffer has to be driven
   * from the element itself or the map ends up letterboxed inside its own pane.
   */
  useEffect(() => {
    const host = mapRef.current;
    if (host === null || typeof ResizeObserver === "undefined") return;
    const observer = new ResizeObserver(() => sceneRef.current?.resize());
    observer.observe(host);
    return () => observer.disconnect();
  }, []);

  useEffect(
    () => () => {
      sceneRef.current?.dispose();
      sceneRef.current = null;
    },
    [],
  );

  useEffect(() => {
    sceneRef.current?.select(selectedNode, selectedEdge);
  }, [selectedEdge, selectedNode]);

  const neuroimage = useCallback(async () => {
    if (chosen.length < 2) return;
    setBusy(true);
    setProgress({ stage: "compare", percent: 0 });
    try {
      // One frame per chunk. `requestAnimationFrame` rather than a timeout so
      // the reading is only ever repainted when the compositor is ready for it,
      // which keeps the run from being slower than the work it reports on.
      const breathe = (): Promise<void> =>
        new Promise((resolve) => window.requestAnimationFrame(() => resolve()));

      // Stage weights: comparison is the O(n²) part and gets most of the bar.
      const weightOf: Record<AnalysisStage, [start: number, span: number]> = {
        compare: [0, 72],
        group: [72, 18],
        place: [90, 6],
        read: [96, 4],
      };

      const { graph, findings } = await analyzeStaged(
        library,
        selection,
        (stage, fraction) => {
          const [start, span] = weightOf[stage];
          setProgress({ stage, percent: Math.min(99, Math.round(start + span * fraction)) });
        },
        breathe,
      );

      setProgress({ stage: "read", percent: 100 });
      setRun({ selection, graph, findings });
      setSelectedNode(null);
      setSelectedEdge(null);
      setDetailId(null);
      sceneRef.current?.setGraph(graph);
      window.setTimeout(() => sceneRef.current?.resize(), 0);

      /**
       * Show the body of work arriving, rather than handing over the finished
       * picture.
       *
       * A completed map is the answer to "what is here" and to nothing else:
       * forty cells and 284 couplings appear at once, fully formed, and a
       * reader has no way in. Every cell and every tract already carries the
       * point in the window at which it was last carrying work, and the
       * playback moves through that window — so the map assembles itself in
       * the order the work actually happened, and the bar underneath counts
       * the cells and couplings that had run by the day on screen. The run
       * ends on the complete picture either way.
       *
       * Three conditions, all of them about not animating into a void. The
       * platform's reduced-motion preference is a veto. The map has to be the
       * view being shown, because the scene owns the clock: on the table
       * nothing would advance it and the reader would be left looking at a
       * static list. And motion is turned on with it, since `setMotion(false)`
       * stops a lapse by design.
       */
      if (!reducedMotion && view === "map") {
        setMotion(true);
        // Start the imperative renderer directly. Waiting for React to commit
        // `motion` and the hook's `playing` state made the first map frame race
        // those effects, leaving an apparently still, sparse render after the
        // button had been pressed.
        sceneRef.current?.setMotion(true);
        sceneRef.current?.restartTimeLapse();
        playRef.current();
      }
    } catch (problem) {
      onError(problem);
    } finally {
      setBusy(false);
      // Held briefly at 100 so the run ends on a number rather than vanishing
      // mid-count, which reads as a failure.
      window.setTimeout(() => setProgress(null), 450);
    }
  }, [chosen.length, library, onError, reducedMotion, selection, view]);

  const graph = report?.graph ?? null;
  const node = graph?.nodes.find((row) => row.id === selectedNode) ?? null;
  const edge = graph?.edges.find((row) => row.id === selectedEdge) ?? null;
  const stale = graph !== null && graph.hash !== hashPreview(selection);

  /**
   * Everything the dialog shows about one IQ Cell.
   *
   * The graph node carries only what the map draws with. The declarations that
   * make a node legible — the files it writes, the paths and hosts it reaches,
   * the model and skills it is configured with, who signs it off — live on the
   * library row, and the connections come from the analysis. All three are read
   * here rather than copied onto the node, so the dialog can never show a
   * figure the report and the table disagree with.
   */
  const detail = useMemo(() => {
    if (graph === null || detailId === null) return null;
    const graphNode = graph.nodes.find((row) => row.id === detailId);
    const cell = library.find((row) => row.id === detailId);
    if (graphNode === undefined || cell === undefined) return null;
    const bundle = graph.bundles.find((row) => row.id === graphNode.bundleId) ?? null;
    const links = graph.edges
      .filter((row) => row.source === detailId || row.target === detailId)
      .sort((a, b) => b.strength - a.strength)
      .slice(0, 6)
      .map((row) => {
        const otherId = row.source === detailId ? row.target : row.source;
        return {
          edge: row,
          otherName: graph.nodes.find((n) => n.id === otherId)?.name ?? otherId,
        };
      });
    return { node: graphNode, cell, bundle, links };
  }, [detailId, graph, library]);

  // Escape closes the dialog, which is the only way out for a keyboard user who
  // opened it and never reaches the close button.
  useEffect(() => {
    if (detail === null) return;
    const onKey = (event: KeyboardEvent): void => {
      if (event.key === "Escape") setDetailId(null);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [detail]);

  /**
   * The time lapse.
   *
   * It replaced a guided tour that flew the camera from one stop to the next.
   * That showed the reader where things *are*, one at a time, and never showed
   * anything happening — a workload steady for a month and one that appeared
   * last Tuesday drew identically, and telling those apart is most of what a
   * picture of your own work is for. The scene owns the playback and reports
   * each frame; this owns the reading.
   */
  const lapse = useTimeLapse(graph);
  pauseRef.current = lapse.pause;
  epochRef.current = lapse.advance;
  playRef.current = lapse.restart;

  useEffect(() => {
    const scene = sceneRef.current;
    if (scene === null) return;
    // A table has nothing to play, and playing into a hidden canvas burns
    // frames to move something nobody is looking at.
    if (lapse.playing && view === "map") scene.playTimeLapse();
    else scene.pauseTimeLapse();
  }, [lapse.playing, view]);

  // Scrubbing is the reader driving the clock, so the scene follows rather
  // than leads. Skipped while playing, where the scene is the source.
  useEffect(() => {
    if (lapse.playing) return;
    sceneRef.current?.setEpoch(lapse.frame.epoch);
  }, [lapse.frame.epoch, lapse.playing]);

  // One switch for everything that moves. Reduced motion is a veto rather than
  // a default, so the platform preference cannot be overridden by the control.
  useEffect(() => {
    sceneRef.current?.setMotion(motion && !reducedMotion);
  }, [motion, reducedMotion]);

  /**
   * Put the picture back the way it was first shown.
   *
   * Everything that moves this surface is one-way otherwise. The time lapse
   * leaves the clock wherever it stopped, and a drag on the map rotates it
   * rather than panning it — neither of which the reader can undo by hand,
   * because there is no "how it was" for them to aim at. So the reset covers
   * all of it: the clock returns to the complete picture, the selection is
   * cleared, and the map goes back to its opening pose.
   */
  const resetView = useCallback((): void => {
    lapse.reset();
    setSelectedNode(null);
    setSelectedEdge(null);
    setDetailId(null);
    sceneRef.current?.select(null, null);
    sceneRef.current?.stopTimeLapse();
    sceneRef.current?.resetView();
  }, [lapse]);

  /**
   * Publish My IQ: hand the library and the analysis to the MCP server other
   * apps read.
   *
   * Only reachable once there is an analysis to publish — a snapshot pinned to
   * a graph that has not been drawn would be a record of nothing.
   *
   * The name and the share answer come from the dialog in front of this, not
   * from anything derived. Connectome IQ lists published IQs by name, and a
   * directory where every row says "My IQ" is a directory with no information
   * in it. Sharing is the publisher's stated intent and changes nothing about
   * what the server serves: the same file, the same five read-only tools.
   *
   * It no longer versions an IQ Cell alongside. An IQ Cell is a business flow
   * somebody drew in IQ Workflow; a coupling analysis is a reading of the
   * library, and filing one as a cell put a card in the library that described
   * the library.
   *
   * The snapshot is written here rather than by a background service because
   * the IQ Cell library lives in this renderer's own storage: nothing else in
   * the app can read it, so this is the only place that can hand it over.
   */
  const publish = useCallback(
    async (name: string, shared: boolean) => {
      if (report === null) return;
      setNotice(null);
      const ok = await publishing.run([
        { label: "Reading the analysis", run: () => {} },
        {
          label: "Publishing over MCP",
          run: async () => {
            const result = await call("myiq:publish", {
              name,
              shared,
              cells: library.map((cell) => ({
                id: cell.id,
                name: cell.name,
                version: cell.version,
                origin: cell.origin,
                faces: cell.faces,
                reach: cell.reach,
                runs: cell.runs,
                completionRate: cell.completionRate,
                approver: cell.approver,
              })),
              connectome: {
                hash: report.graph.hash,
                nodeCount: report.graph.nodes.length,
                edgeCount: report.graph.edges.length,
                windowDays: report.selection.windowDays,
                findings: report.findings.map((finding) => ({
                  kind: finding.kind,
                  title: finding.title,
                  detail: finding.detail,
                  action: finding.action,
                })),
                limits: report.limits,
                generatedAt: report.generatedAt,
              },
            });
            setPublished(result);
          },
        },
      ]);
      if (!ok) return;
      setNotice(
        `${name} is published: ${library.length} IQ Cells and the analysis of ${report.graph.nodes.length}.` +
          (shared ? " It is listed in Connectome IQ as shared." : " It is not shared with anyone."),
      );
    },
    [publishing, library, report],
  );

  /**
   * The publish dialog arrives after a pause, not with the notice.
   *
   * They say different things and the second is the one with something to act
   * on: the notice reports what went out, this reports that My IQ is now
   * readable from another app and hands over the configuration to do it. Landing
   * both at once buries the second under the first.
   *
   * Keyed on the result object, so a second publish raises it again, and the
   * timer is cleared on unmount — navigating away from the Connectome during
   * the pause must not set state on a component that is gone.
   */
  useEffect(() => {
    if (published === null) return;
    const timer = window.setTimeout(() => setShowPublished(true), PUBLISH_DIALOG_DELAY_MS);
    return () => window.clearTimeout(timer);
  }, [published]);

  /**
   * Open an IQ Cell where it was made.
   *
   * The map answers "how does this relate to the rest"; what the cell actually
   * *is* is a different question, and this is the way across. Where across goes
   * is `routeForCell`'s answer, because the origins are not variations on one
   * another: an editor cell is a procedure someone drew, so the canvas is the
   * answer; a knowledge cell is the index, published so it can be asked
   * questions; a memory cell is a convention. Sending all three to a canvas
   * nobody drew on answered a question two of them were not asked.
   *
   * For an editor cell the draft is rebuilt from the IQ Cell's own declarations
   * because the demo library has no stored source — the Editor says so when it
   * opens it. That reconstruction is the only part of the decision that is this
   * surface's own.
   */
  const openCell = useCallback(
    (cell: DemoIqCell) => {
      try {
        const route = routeForCell(cell.origin, cell.originRef ?? []);
        if (route.kind === "editor") {
          stageForEditor(projectId, draftFromCell(cell, projectId));
        }
        onOpenCell(route);
      } catch (problem) {
        onError(problem);
      }
    },
    [onError, onOpenCell, projectId],
  );

  return (
    <div className="connectome">
      <header className="flow-head">
        <span className="flow-title">
          <Brain size={16} aria-hidden="true" />
          <strong>My IQ</strong>
        </span>
        <span className="flow-tagline">Your knowledge, intelligence, and workflows.</span>
        <span className="chip beta">Beta · demo data</span>
        {graph !== null && (
          <span className="flow-hash" title="Graph hash — the same selection always gives this">
            {graph.hash}
          </span>
        )}
        <span className="spacer" />
        {/* What this surface is about to do, before it does it. The map has no
            account of itself once it is drawn, and a graph you cannot check is
            a graph you have to trust. */}
        <button
          className={`ghost${showInstructions ? " active" : ""}`}
          onClick={() => setShowInstructions(true)}
          title="How My IQ is built — and your own notes on how it should be"
        >
          <BookOpen size={14} aria-hidden="true" /> Instructions
        </button>
        <label className="field inline">
          <span>Window</span>
          <select
            value={windowDays}
            onChange={(event) => setWindowDays(Number(event.target.value))}
          >
            {[7, 30, 90].map((days) => (
              <option key={days} value={days}>
                {days} days
              </option>
            ))}
          </select>
        </label>
        {/* Reading, not re-running. The dropdown takes effect immediately —
            there is no second analysis behind it, because the graph is the
            same graph whoever is looking at it. */}
        <label className="field inline">
          <span>Persona</span>
          <select
            value={persona}
            onChange={(event) => setPersona(event.target.value as ConnectomePersona)}
            title={`${lens.question} Orders the findings for this reader; hides none of them.`}
          >
            {ConnectomePersona.options.map((key) => (
              <option key={key} value={key}>
                {CONNECTOME_PERSONAS[key].label}
              </option>
            ))}
          </select>
        </label>
        <button
          className={`ghost${listOpen ? " active" : ""}`}
          onClick={() => setListOpen(!listOpen)}
          aria-label={listOpen ? "Hide IQ Cells" : "Show IQ Cells"}
          title="Choose the IQ Cells to compare"
        >
          <Boxes size={14} aria-hidden="true" /> IQ Cells
        </button>
        <button
          className="ghost"
          onClick={() => sceneRef.current?.zoomToFit()}
          disabled={view !== "map"}
          aria-label="Zoom to fit"
          title="Zoom to fit"
        >
          <Maximize2 size={14} aria-hidden="true" />
        </button>
        <button
          className={`ghost${motion ? " active" : ""}`}
          onClick={() => setMotion(!motion)}
          disabled={view !== "map" || graph === null || reducedMotion}
          aria-label={motion ? "Stop the animation" : "Animate the traffic"}
          title={
            reducedMotion
              ? "Animation stays off because this device asks for reduced motion"
              : motion
                ? "Stop the animation — the still picture carries the same information"
                : "Animate the traffic between IQ Cells"
          }
        >
          {motion ? <Pause size={14} aria-hidden="true" /> : <Play size={14} aria-hidden="true" />}
        </button>
        <button
          className="ghost"
          onClick={() => (lapse.playing ? lapse.pause() : lapse.play())}
          disabled={view !== "map" || graph === null}
          title="Play the time lapse — the body of work assembling over the window"
        >
          <RefreshCw size={14} aria-hidden="true" />
        </button>
        {/* Two openers for one column, because they answer different
            questions: "what did it find" and "let me ask it something". Each
            opens the column onto its own side, and clicking the one already
            showing closes the column again. */}
        <button
          className={`ghost${rightOpen && rightPane === "report" ? " active" : ""}`}
          onClick={() => {
            if (rightOpen && rightPane === "report") setRightOpen(false);
            else {
              setRightPane("report");
              setRightOpen(true);
            }
          }}
          aria-label={rightOpen && rightPane === "report" ? "Hide the report" : "Show the report"}
          title="The findings, the weights and the limits of this analysis"
        >
          <FileText size={14} aria-hidden="true" /> Report
        </button>
        <button
          className={`ghost${rightOpen && rightPane === "chat" ? " active" : ""}`}
          onClick={() => {
            if (rightOpen && rightPane === "chat") setRightOpen(false);
            else {
              setRightPane("chat");
              setRightOpen(true);
            }
          }}
          aria-label={rightOpen && rightPane === "chat" ? "Hide the chat" : "Ask about the map"}
          title="Ask about the map — answered from this analysis, not from a model"
        >
          <MessageSquare size={14} aria-hidden="true" /> Chat
        </button>
        <button
          className="ghost"
          onClick={() => setNaming(true)}
          disabled={report === null || publishing.busy}
          title={
            report === null
              ? "Draw the map first — a snapshot of an analysis that has not run is a record of nothing"
              : "Name this IQ and serve it — this library and this analysis — to other apps over MCP"
          }
        >
          <Boxes size={14} aria-hidden="true" />{" "}
          {publishing.busy ? stepLabel(publishing, "Publish") : "Publish"}
        </button>
        <button
          className="primary"
          onClick={() => void neuroimage()}
          disabled={busy || chosen.length < 2}
          title="Compare every selected pair on the six declared signals and draw the result"
        >
          <Sparkles size={14} aria-hidden="true" />{" "}
          {busy && progress !== null ? `${progress.percent}%` : "Analyse"}
        </button>
      </header>

      {notice !== null && <p className="notice connectome-notice">{notice}</p>}

      {showInstructions && (
        <InstructionsDialog
          text={instructions}
          fallback={DEFAULT_INSTRUCTIONS}
          onCancel={() => setShowInstructions(false)}
          onSave={saveInstructions}
        />
      )}

      {naming && (
        <PublishDialog
          cellCount={library.length}
          onCancel={() => setNaming(false)}
          onPublish={(name, shared) => {
            setNaming(false);
            void publish(name, shared);
          }}
        />
      )}

      {showPublished && published !== null && (
        <PublishedDialog result={published} onClose={() => setShowPublished(false)} />
      )}

      <div
        className="connectome-body"
        ref={split.containerRef}
        style={{ gridTemplateColumns: split.template }}
      >
        {listOpen && (
          <>
            <aside className="connectome-list">
          <div className="row between">
            <strong>IQ Cells</strong>
            <span className="muted">{chosen.length}/{library.length}</span>
          </div>
          <div className="row">
            <button className="link" onClick={() => setChosen(library.map((row) => row.id))}>
              All
            </button>
            <button className="link" onClick={() => setChosen([])}>
              None
            </button>
            <button
              className="link"
              onClick={() =>
                setChosen(
                  library.filter((row) => row.faces.includes("automation")).map((row) => row.id),
                )
              }
            >
              Automations
            </button>
          </div>

          <ul>
            {library.map((row) => (
              <li key={row.id} className={selectedNode === row.id ? "selected" : ""}>
                <label>
                  <input
                    type="checkbox"
                    checked={chosen.includes(row.id)}
                    onChange={(event) =>
                      setChosen((current) =>
                        event.target.checked
                          ? [...current, row.id]
                          : current.filter((id) => id !== row.id),
                      )
                    }
                  />
                  {/* Selecting from the list, not only from the picture.

                      The map is a canvas, so picking a node there means
                      hitting a raycast target whose screen position depends on
                      the GPU, the window size and how far the reveal has run.
                      The list is where a reader looks something up by name, and
                      it is the only place on this surface where that is a
                      certain act. */}
                  <button
                    className="name"
                    title={`Select ${row.name}`}
                    onClick={() => {
                      lapse.pause();
                      setSelectedNode(row.id);
                      setSelectedEdge(null);
                      sceneRef.current?.select(row.id, null);
                      sceneRef.current?.focusOn(row.id, null);
                    }}
                  >
                    {row.name}
                  </button>
                </label>
                <span className="muted">
                  v{row.version} · {row.runs} runs · {(row.completionRate * 100).toFixed(0)}% ·{" "}
                  {row.tokensPerRun.toLocaleString()} tok
                </span>
                <span className={`chip origin ${row.origin}`}>
                  {IQ_CELL_ORIGIN_LABELS[row.origin]}
                </span>
                {/* The map says how this IQ Cell relates to the others; the
                    surface it came from says what it actually does. This is
                    the way across, and it goes where the cell was made. */}
                <button
                  className="icon row-edit"
                  title={`Open ${row.name} in ${IQ_CELL_ORIGIN_LABELS[row.origin]}`}
                  aria-label={`Open ${row.name} in ${IQ_CELL_ORIGIN_LABELS[row.origin]}`}
                  onClick={() => openCell(row)}
                >
                  <Pencil size={14} aria-hidden="true" />
                </button>
              </li>
            ))}
          </ul>
            </aside>

            <SplitDivider
              label="Resize IQ Cell list"
              onPointerDown={(event) => split.startDrag("list", event)}
            />
          </>
        )}

        <div className="connectome-map">
          <div className="map-tabs">
            {(["map", "table"] as const).map((option) => (
              <button
                key={option}
                className={view === option ? "active" : ""}
                onClick={() => setView(option)}
                disabled={option === "map" && !webglAvailable()}
                title={VIEW_HINTS[option]}
              >
                {VIEW_LABELS[option]}
              </button>
            ))}
            <span className="spacer" />
            <span className="muted">{VIEW_HINTS[view]}</span>
          </div>

          {/* The run, on the surface it is drawing. Named phases and a real
              count, because "please wait" tells a reader nothing about whether
              to keep waiting. */}
          {progress !== null && (
            <div className="map-progress" role="status" aria-live="polite">
              <div className="map-progress-head">
                <strong>{progress.percent}%</strong>
                <span>{ANALYSIS_STAGES.find((s) => s.key === progress.stage)?.label}</span>
              </div>
              <div
                className="map-progress-track"
                role="progressbar"
                aria-valuenow={progress.percent}
                aria-valuemin={0}
                aria-valuemax={100}
              >
                <div className="map-progress-fill" style={{ width: `${progress.percent}%` }} />
              </div>
              <div className="map-progress-steps">
                {ANALYSIS_STAGES.map((stage) => (
                  <span
                    key={stage.key}
                    className={
                      stage.key === progress.stage
                        ? "now"
                        : ANALYSIS_STAGES.findIndex((s) => s.key === stage.key) <
                            ANALYSIS_STAGES.findIndex((s) => s.key === progress.stage)
                          ? "done"
                          : ""
                    }
                  >
                    {stage.key}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* The time lapse transport.

              It replaced a guided tour that flew the camera between stops.
              That answered "where is this one" a stop at a time and never
              showed change, which is the thing a map of a *body of work* is
              for: at the far end of the window this graph is nearly empty, and
              watching it fill is what says which parts of the work are alive.

              Shown with the map only. The table is a sorted list of every
              connection, which the clock does not move. */}
          {graph !== null && view === "map" && (
            <div className={`tour-bar timelapse${lapse.playing ? " playing" : ""}`}>
              <button
                className="icon"
                onClick={() => (lapse.playing ? lapse.pause() : lapse.play())}
                title={lapse.playing ? "Pause the time lapse" : "Play the time lapse"}
                aria-label={lapse.playing ? "Pause the time lapse" : "Play the time lapse"}
              >
                {lapse.playing ? (
                  <Pause size={14} aria-hidden="true" />
                ) : (
                  <Play size={14} aria-hidden="true" />
                )}
              </button>
              {/* The way back. Every other control on this bar moves the camera
                  or the clock, and dragging the map rotates it rather than
                  panning it, so without this the opening view is a place the
                  reader can leave and never return to. */}
              <button
                className="icon"
                onClick={resetView}
                title="Back to the opening view — returns the clock to today and undoes any rotation, zoom or dragging"
                aria-label="Back to the opening view"
              >
                <RotateCcw size={14} aria-hidden="true" />
              </button>
              <input
                className="timelapse-scrub"
                type="range"
                min={0}
                max={1000}
                step={1}
                value={Math.round(lapse.frame.epoch * 1000)}
                aria-label="Time lapse position"
                onChange={(event) => lapse.scrub(Number(event.target.value) / 1000)}
              />
              <span className="tour-copy">
                <strong>{lapse.frame.label}</strong>
                {/* Counted rather than described: "18 of 45 IQ Cells" is the
                    claim the picture is making at this moment, and a reader can
                    check it against the list beside them. */}
                <span className="muted">
                  {lapse.frame.cells} of {lapse.total.cells} IQ Cells ·{" "}
                  {lapse.frame.couplings} of {lapse.total.couplings} couplings had run
                </span>
              </span>
              <span className="tour-count mono">
                {lapse.frame.daysAgo === 0 ? "now" : `−${lapse.frame.daysAgo}d`}
              </span>
            </div>
          )}

          {/* Both surfaces stay mounted; only one is shown. The map's
              canvas in particular must not be torn down and rebuilt. */}
          <div className="map-surface" ref={mapRef} hidden={view !== "map"}>
            <canvas ref={canvasRef} aria-label="My IQ map" />
            {/* Names for the nodes, as HTML over the canvas. Hidden from
                assistive technology: the same cells are listed beside the map,
                where they can be read in order and reached by keyboard. */}
            <div className="map-labels" ref={labelsRef} aria-hidden="true" />
            {graph === null && (
              <div className="map-placeholder">
                <strong>{estimate.nodes} IQ Cells selected</strong>
                <span className="muted">
                  {estimate.pairs.toLocaleString()} candidate pairs over{" "}
                  {estimate.runs.toLocaleString()} recorded runs. Press Analyse to
                  compare them.
                </span>
              </div>
            )}
            {stale && view === "map" && (
              <div className="map-stale">Selection changed — press Analyse to refresh.</div>
            )}
            {graph !== null && (
              /* Folded away by default.

                 It is a key to an encoding, which is a thing you read once and
                 then stop needing — and open it covered the bottom third of the
                 picture it was explaining. The picture is the point; the key is
                 one click away and stays open once opened. */
              <details className="map-legend">
                <summary>What the picture encodes</summary>
                <dl>
                  <div>
                    <dt>Line colour</dt>
                    <dd>Which group the pair belongs to</dd>
                  </div>
                  <div>
                    <dt>Line thickness</dt>
                    <dd>How strongly they are coupled</dd>
                  </div>
                  <div>
                    <dt>Line brightness</dt>
                    <dd>How recently both ran</dd>
                  </div>
                  <div>
                    <dt>Travelling light</dt>
                    <dd>Direction of the pairing, faster on stronger couplings</dd>
                  </div>
                  <div>
                    <dt>Node core</dt>
                    <dd>Which group it belongs to</dd>
                  </div>
                  <div>
                    <dt>Node size</dt>
                    <dd>Number of runs</dd>
                  </div>
                  <div>
                    <dt>Node glow</dt>
                    <dd>Its group colour, intensified by completion</dd>
                  </div>
                  <div>
                    <dt>Node flash</dt>
                    <dd>Its strongest incoming pairing delivering</dd>
                  </div>
                  <div>
                    <dt>Node name</dt>
                    <dd>
                      Shortened; the busiest are named, and selecting one names it and everything
                      it is paired with
                    </dd>
                  </div>
                </dl>
              </details>
            )}
          </div>

          <div className="map-surface table" hidden={view !== "table"}>
            {graph === null ? (
              <p className="muted">Press Analyse to compare the selection.</p>
            ) : (
              <table className="grid">
                <thead>
                  <tr>
                    <th>Connection</th>
                    <th>How it was found</th>
                    <th>Strength</th>
                    <th>Because</th>
                  </tr>
                </thead>
                <tbody>
                  {[...graph.edges]
                    .sort((a, b) => b.strength - a.strength)
                    .map((row) => (
                      <tr
                        key={row.id}
                        className={selectedEdge === row.id ? "selected" : ""}
                        onClick={() => {
                          setSelectedEdge(row.id);
                          setSelectedNode(null);
                          setDetailId(null);
                        }}
                      >
                        <td>
                          {graph.nodes.find((n) => n.id === row.source)?.name} ↔{" "}
                          {graph.nodes.find((n) => n.id === row.target)?.name}
                        </td>
                        <td>{ORIGIN_LABELS[row.origin]}</td>
                        <td>{(row.strength * 100).toFixed(0)}%</td>
                        <td className="muted">
                          {row.evidence.map((item) => item.detail).join("; ")}
                        </td>
                      </tr>
                    ))}
                </tbody>
              </table>
            )}
          </div>
        </div>

        {rightOpen && (
          <>
        <SplitDivider
          label="Resize report"
          onPointerDown={(event) => split.startDrag("report", event)}
        />

        <aside className="connectome-report">
          {/* One column, two things to do with it. The switch is here as well
              as in the header so the reader can get back without hunting. */}
          <div className="map-tabs">
            <button
              className={rightPane === "report" ? "active" : ""}
              onClick={() => setRightPane("report")}
            >
              Report
            </button>
            <button
              className={rightPane === "chat" ? "active" : ""}
              onClick={() => setRightPane("chat")}
            >
              Chat
            </button>
            <span className="spacer" />
            <button
              className="ghost"
              onClick={() => setRightOpen(false)}
              aria-label="Hide the report column"
              title="Hide this column and give the space back to the map"
            >
              <ChevronRight size={14} aria-hidden="true" />
            </button>
          </div>

          {rightPane === "chat" ? (
            <ConnectomeChat
              report={report}
              persona={persona}
              onSelectNode={(id) => {
                lapse.pause();
                setSelectedNode(id);
                setSelectedEdge(null);
                sceneRef.current?.select(id, null);
                sceneRef.current?.focusOn(id, null);
              }}
              onSelectEdge={(id) => {
                lapse.pause();
                setSelectedEdge(id);
                setSelectedNode(null);
                sceneRef.current?.select(null, id);
                sceneRef.current?.focusOn(null, id);
              }}
            />
          ) : (
            <>
          {/* The surface says how it was made before it says what it found. A
              strength figure nobody can reproduce is not evidence. */}
          <details className="card how" open={graph === null}>
            <summary>How this is built</summary>
            <ol className="how-steps">
              <li>
                Take the {chosen.length} IQ Cells ticked on the left, over the last {windowDays}{" "}
                days of run history.
              </li>
              <li>
                Compare every pair — {estimate.pairs.toLocaleString()} of them — on six signals
                they already declare. Nothing is read from inside an artifact and no model is
                asked.
              </li>
              <li>
                Multiply each signal by its weight below and add them up. That sum, divided by the
                maximum possible, is the strength. Pairs below {(LATENT_FLOOR * 100).toFixed(0)}%
                are dropped as noise.
              </li>
              <li>
                Group the survivors by repeatedly moving each IQ Cell to whichever group its
                strongest neighbours are already in. Those groups are the coloured bundles.
              </li>
              <li>
                Positions come from the graph hash <code>{graph?.hash ?? "—"}</code>, so the same
                selection always draws the same picture.
              </li>
            </ol>
            <p className="muted">
              An edge is either <strong>declared</strong> — one IQ Cell literally embeds the other —
              or <strong>inferred</strong>, which is a hypothesis with its reasons attached. An
              inferred edge grants nothing and changes no execution.
            </p>
          </details>

          {node !== null && (
            <div className="card">
              <div className="row between">
                <h3>{node.name}</h3>
                <button className="ghost" onClick={() => setDetailId(node.id)}>
                  Details
                </button>
              </div>
              <p className="muted">
                v{node.version} · {node.runs} runs · {(node.completionRate * 100).toFixed(0)}%
                completion
              </p>
              <p>Reach: {node.reach.join(", ") || "none declared"}</p>
              <p className="muted">
                Group: {graph?.bundles.find((b) => b.id === node.bundleId)?.name ?? "—"}
              </p>
            </div>
          )}

          {edge !== null && (
            <div className="card">
              <h3>Connection</h3>
              <p>
                {graph?.nodes.find((n) => n.id === edge.source)?.name} ↔{" "}
                {graph?.nodes.find((n) => n.id === edge.target)?.name}
              </p>
              <p className="muted">
                {ORIGIN_LABELS[edge.origin]} · {(edge.strength * 100).toFixed(0)}% strength ·{" "}
                {(edge.recency * 100).toFixed(0)}% recent
              </p>
              {/* The arithmetic, term by term, so the number can be checked
                  rather than believed. */}
              <table className="grid dense">
                <thead>
                  <tr>
                    <th>Signal</th>
                    <th>Match</th>
                    <th>× weight</th>
                  </tr>
                </thead>
                <tbody>
                  {edge.evidence.map((item, index) => (
                    <tr key={index}>
                      <td>
                        <strong>{COUPLING_LABELS[item.component]}</strong>
                        <span className="muted"> — {item.detail}</span>
                      </td>
                      <td className="mono">{item.score.toFixed(2)}</td>
                      <td className="mono">
                        {(item.score * (weights[item.component] ?? 0)).toFixed(2)}
                      </td>
                    </tr>
                  ))}
                  <tr>
                    <td>Sum ÷ the most any pair could score</td>
                    <td />
                    <td className="mono">{edge.strength.toFixed(2)}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          )}

          <div className="card">
            <h3>Weights</h3>
            <p className="muted">
              How much each signal counts toward strength. Change one and press Analyse
              again — the values are printed in the exported report.
            </p>
            {WEIGHT_KEYS.map((key) => (
              <label className="field slider" key={key}>
                <span>
                  {COUPLING_LABELS[key]} <em>{weights[key].toFixed(2)}</em>
                </span>
                <span className="how-line">{COUPLING_HOW[key]}</span>
                <input
                  type="range"
                  min={0}
                  max={1}
                  step={0.05}
                  value={weights[key]}
                  onChange={(event) =>
                    setWeights((current) => ({ ...current, [key]: Number(event.target.value) }))
                  }
                />
              </label>
            ))}
          </div>

          {report !== null && (
            <>
              <div className="card">
                <div className="row between">
                  <h3>Report</h3>
                  <button
                    className="ghost"
                    onClick={() =>
                      download(`iq-connectome-${report.graph.hash}.md`, report.markdown)
                    }
                  >
                    <Download size={14} aria-hidden="true" /> Export
                  </button>
                </div>
                <p className="muted">
                  {report.graph.nodes.length} IQ Cells · {report.graph.edges.length} connections ·{" "}
                  {report.graph.bundles.length} groups
                </p>
              </div>

              <div className="card">
                <h3>Groups</h3>
                <p className="muted">
                  Clusters of IQ Cells that are more strongly coupled to each other than to the
                  rest. Named after whatever they most have in common.
                </p>
                {report.graph.bundles.map((bundle) => (
                  <div className="bundle-row" key={bundle.id}>
                    <span className="swatch" style={{ background: `hsl(${bundle.hue} 70% 52%)` }} />
                    <strong>{bundle.name}</strong>
                    <span className="muted">
                      {bundle.members.length} members · {(bundle.costShare * 100).toFixed(0)}% cost
                    </span>
                  </div>
                ))}
              </div>

              <div className="card">
                <h3>Findings</h3>
                <p className="muted">
                  Persona: <strong>{lens.label}</strong> — {lens.question} Ordered for that
                  reader, never filtered for them: {lens.blindSpot}
                </p>
                {report.findings.length === 0 && <p className="muted">Nothing to report.</p>}
                {report.findings.map((finding, index) => (
                  <div className="finding" key={index}>
                    <span className={`tag ${finding.kind}`}>{finding.kind.replace(/_/g, " ")}</span>
                    <strong>{finding.title}</strong>
                    <span className="muted">{finding.detail}</span>
                    <span className="action">{finding.action}</span>
                  </div>
                ))}
              </div>

              <div className="card">
                <h3>Coverage and limits</h3>
                <ul>
                  {report.limits.map((limit, index) => (
                    <li key={index} className="muted">
                      {limit}
                    </li>
                  ))}
                </ul>
              </div>
            </>
          )}
            </>
          )}
        </aside>
          </>
        )}
      </div>

      {detail !== null && (
        <NodeDialog
          detail={detail}
          onClose={() => setDetailId(null)}
          onOpenEdge={(id) => {
            setDetailId(null);
            setSelectedEdge(id);
            setSelectedNode(null);
          }}
          onOpenNode={(id) => {
            setDetailId(id);
            setSelectedNode(id);
            setSelectedEdge(null);
          }}
        />
      )}
    </div>
  );
}

interface NodeDetail {
  node: ConnectomeNode;
  cell: DemoIqCell;
  bundle: ConnectomeBundle | null;
  links: { edge: ConnectomeEdge; otherName: string }[];
}

/**
 * What one IQ Cell is, on top of the map.
 *
 * The dialog answers the question a blob cannot: what job is this, who signs
 * it off, what does it touch, and what is it tied to. Every line is a
 * declaration the IQ Cell already carries or a number the analysis already
 * published — nothing here is computed for the dialog alone, so it can never
 * disagree with the report or the connection table.
 */
function NodeDialog({
  detail,
  onClose,
  onOpenEdge,
  onOpenNode,
}: {
  detail: NodeDetail;
  onClose: () => void;
  onOpenEdge: (id: string) => void;
  onOpenNode: (id: string) => void;
}): JSX.Element {
  const { node, cell, bundle, links } = detail;
  const closeRef = useRef<HTMLButtonElement | null>(null);

  // The dialog is opened by a click on a canvas, which leaves focus on the
  // canvas. Moving it here is what lets Tab reach the contents and Escape feel
  // like it belongs to the dialog rather than to the map behind it.
  useEffect(() => {
    closeRef.current?.focus();
  }, []);

  const facts: [string, string][] = [
    ["Recorded in", IQ_CELL_ORIGIN_LABELS[cell.origin]],
    ["Runs", node.runs.toLocaleString()],
    ["Completed", `${(node.completionRate * 100).toFixed(0)}%`],
    ["Tokens per run", node.tokensPerRun.toLocaleString()],
    ["Last run", cell.lastRunDaysAgo === 0 ? "today" : `${cell.lastRunDaysAgo} days ago`],
    ["Approver", cell.approver],
    ["Version", `v${node.version}${cell.pinnedVersionsBehind > 0 ? ` · ${cell.pinnedVersionsBehind} behind where it is pinned` : ""}`],
  ];

  return (
    // The scrim closes on click, which is the gesture a reader reaches for
    // first after opening something over a picture they were looking at.
    <div className="node-dialog-scrim" onClick={onClose}>
      <div
        className="node-dialog"
        role="dialog"
        aria-modal="true"
        aria-label={`${node.name} — IQ Cell details`}
        onClick={(event) => event.stopPropagation()}
      >
        <header className="node-dialog-head">
          <span
            className="swatch"
            style={{ background: `hsl(${bundle?.hue ?? 210} 70% 52%)` }}
            aria-hidden="true"
          />
          <span className="node-dialog-title">
            <strong>{node.name}</strong>
            <span className="muted">
              {bundle?.name ?? "ungrouped"} · {node.faces.join(" · ")}
            </span>
          </span>
          <button className="icon" ref={closeRef} onClick={onClose} aria-label="Close details">
            <X size={14} aria-hidden="true" />
          </button>
        </header>

        <div className="node-dialog-body">
          <dl className="node-facts">
            {facts.map(([label, value]) => (
              <div key={label}>
                <dt>{label}</dt>
                <dd>{value}</dd>
              </div>
            ))}
          </dl>

          <NodeDialogChips label="Reach" items={node.reach} empty="Nothing outside the project." />
          <NodeDialogChips
            label="Writes"
            items={cell.producesArtifacts}
            empty="Writes no artifact."
          />
          <NodeDialogChips label="Reads" items={cell.consumesArtifacts} empty="Reads no artifact." />
          <NodeDialogChips label="Project paths" items={cell.paths} empty="No declared paths." />
          <NodeDialogChips label="Hosts" items={cell.hosts} empty="No outside hosts." />
          <NodeDialogChips
            label="Configuration"
            items={cell.configuration}
            empty="Nothing named."
          />

          <div className="node-links">
            <h4>Strongest connections</h4>
            {links.length === 0 && (
              <p className="muted">
                Nothing crossed the noise floor. This IQ Cell stands on its own in this selection.
              </p>
            )}
            {links.map(({ edge, otherName }) => (
              <button
                key={edge.id}
                className="node-link"
                onClick={() => onOpenEdge(edge.id)}
                title="Open this connection in the report"
              >
                <span className="node-link-name">{otherName}</span>
                <span className="mono">{(edge.strength * 100).toFixed(0)}%</span>
                <span className="muted">
                  {ORIGIN_LABELS[edge.origin]} — {edge.evidence[0]?.detail ?? "no evidence"}
                </span>
              </button>
            ))}
          </div>

          {cell.embeds.length > 0 && (
            <div className="node-links">
              <h4>Embeds</h4>
              {cell.embeds.map((id) => (
                <button key={id} className="node-link" onClick={() => onOpenNode(id)}>
                  <span className="node-link-name">{id}</span>
                  <span className="muted">Declared — this IQ Cell pins it as a node</span>
                </button>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

/** One labelled row of declarations, or the honest statement that there are none. */
function NodeDialogChips({
  label,
  items,
  empty,
}: {
  label: string;
  items: readonly string[];
  empty: string;
}): JSX.Element {
  return (
    <div className="node-chips">
      <h4>{label}</h4>
      {items.length === 0 ? (
        <p className="muted">{empty}</p>
      ) : (
        <span className="chips">
          {items.map((item) => (
            <span className="chip" key={item}>
              {item}
            </span>
          ))}
        </span>
      )}
    </div>
  );
}

/** Cheap preview of the analysis hash, used only to mark the map stale. */
const hashPreview = (selection: ConnectomeSelection): string => {
  const input = JSON.stringify({
    ids: [...selection.iqCellIds].sort(),
    window: selection.windowDays,
    weights: { ...DEFAULT_CONNECTOME_WEIGHTS, ...selection.weights },
  });
  let hash = 0x811c9dc5;
  for (let index = 0; index < input.length; index += 1) {
    hash ^= input.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, "0");
};

const download = (name: string, text: string): void => {
  const url = URL.createObjectURL(new Blob([text], { type: "text/markdown" }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  URL.revokeObjectURL(url);
};

/**
 * How My IQ gets built, and the reader's own account of how it should be.
 *
 * The default is the app describing itself. The textarea is there because that
 * description is not always the whole story: a team compiling from a different
 * kind of material, or with a rule about what may go in, has something to say
 * about this build that the code cannot know. Rather than a read-only
 * explainer beside a wiki nobody opens, the explanation and the house rules
 * are the same piece of text, in the place the build happens.
 *
 * **Restore the default** is the way back. Editing prose in a box with no undo
 * is a one-way door otherwise, and someone who has overwritten the recipe has
 * lost the recipe.
 *
 * Not built on {@link Modal}, for the same reason {@link PublishDialog} is
 * not: that dialog's own button closes it, and here closing and saving have to
 * be two different buttons.
 */
function InstructionsDialog({
  text,
  fallback,
  onCancel,
  onSave,
}: {
  text: string;
  fallback: string;
  onCancel: () => void;
  onSave: (text: string) => void;
}): JSX.Element {
  const [draft, setDraft] = useState(text);

  useEffect(() => {
    const onKey = (event: KeyboardEvent): void => {
      if (event.key === "Escape") onCancel();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onCancel]);

  return (
    <>
      <div className="modal-scrim" onClick={onCancel} />
      <div className="modal-card instructions" role="dialog" aria-modal="true" aria-label="How My IQ is built">
        <div className="modal-head">
          <strong>How My IQ is built</strong>
        </div>
        <div className="modal-body">
          <textarea
            className="instructions-text"
            value={draft}
            aria-label="Build instructions"
            spellCheck={false}
            onChange={(event) => setDraft(event.target.value)}
          />
          <p className="muted">
            This is a description, not a setting. Editing it changes what is written here and
            nothing about what Analyse does.
          </p>
        </div>
        <div className="modal-foot">
          <button onClick={() => setDraft(fallback)} disabled={draft === fallback}>
            <RotateCcw size={14} aria-hidden="true" /> Restore the default
          </button>
          <span className="spacer" />
          <button onClick={onCancel}>Cancel</button>
          <button className="primary" onClick={() => onSave(draft)}>
            Save
          </button>
        </div>
      </div>
    </>
  );
}

/**
 * What is about to leave the app, and under what name.
 *
 * Publishing used to be one click with nothing to decide, which made two
 * questions unanswerable afterwards: what is this IQ called, and did the person
 * mean it for anyone else. Connectome IQ lists published IQs by name, so both
 * have to be asked before the file is written rather than inferred from it.
 *
 * Sharing changes nothing about what the MCP server serves — the same file, the
 * same five read-only tools. It is a stated intent, and the copy says so
 * plainly rather than implying a permission boundary that does not exist here.
 *
 * Not built on {@link Modal}: that dialog's own button closes it, which is the
 * right shape for reporting a result and the wrong one for a form, where the
 * closing action and the committing action have to be different buttons.
 */
function PublishDialog({
  cellCount,
  onCancel,
  onPublish,
}: {
  cellCount: number;
  onCancel: () => void;
  onPublish: (name: string, shared: boolean) => void;
}): JSX.Element {
  const [name, setName] = useState(MYIQ_DEFAULT_NAME);
  const [shared, setShared] = useState(true);
  const field = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    field.current?.select();
    const onKey = (event: KeyboardEvent): void => {
      if (event.key === "Escape") onCancel();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onCancel]);

  const trimmed = name.trim();

  return (
    <>
      <div className="modal-scrim" onClick={onCancel} />
      <div className="modal-card" role="dialog" aria-modal="true" aria-label="Publish My IQ">
        <div className="modal-head">
          <strong>Publish My IQ</strong>
        </div>
        <div className="modal-body">
          <label className="field">
            <span>Name</span>
            <input
              ref={field}
              value={name}
              autoFocus
              onChange={(event) => setName(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === "Enter" && trimmed !== "") onPublish(trimmed, shared);
              }}
            />
          </label>
          <label className="tool-grant">
            <input
              type="checkbox"
              checked={shared}
              onChange={(event) => setShared(event.target.checked)}
            />
            <span>Share this IQ in Connectome IQ</span>
          </label>
          <p className="muted">
            {shared
              ? "It is listed in Connectome IQ as shared, beside the IQs other people share."
              : "It is listed in Connectome IQ as yours only, and offered to nobody."}{" "}
            Either way it is served the same: {cellCount} IQ Cells, your sample memories and
            knowledge notes, read-only, over MCP.
          </p>
        </div>
        <div className="modal-foot">
          <button onClick={onCancel}>Cancel</button>
          <button className="primary" disabled={trimmed === ""} onClick={() => onPublish(trimmed, shared)}>
            Publish
          </button>
        </div>
      </div>
    </>
  );
}

/**
 * What happened, and what someone can now do with it.
 *
 * The wording is careful not to overclaim. Publishing wrote a file and nothing
 * is running: the server starts when another app spawns it, which is why the
 * configuration is the substance of this dialog rather than a footnote. It also
 * says plainly that the material is sample data, because the whole point of the
 * feature is to show the shape of the integration, and someone who took it for
 * their real workload would draw the wrong conclusion about what just left the
 * app.
 */
function PublishedDialog({
  result,
  onClose,
}: {
  result: MyIqPublishResult;
  onClose: () => void;
}): JSX.Element {
  const [copied, setCopied] = useState(false);
  const status = result.status;

  const copy = (): void => {
    void navigator.clipboard
      .writeText(status.endpoint.clientConfig)
      .then(() => setCopied(true))
      .catch(() => setCopied(false));
  };

  return (
    <Modal
      title={`${status.name} is published over MCP`}
      onClose={onClose}
      footer={
        <button onClick={copy}>{copied ? "Copied" : "Copy configuration"}</button>
      }
    >
      <p>
        {status.cellCount} IQ Cells, {status.memoryCount} memories and {status.noteCount}{" "}
        knowledge notes are now readable by any app that speaks MCP
        {status.hasConnectome ? ", along with this analysis" : ""}.
      </p>
      <p className="muted">
        {status.shared
          ? "It is listed in Connectome IQ as shared."
          : "It is listed in Connectome IQ as yours only."}{" "}
        This is sample data, and it is read-only — the five tools list and read, and there
        is no way to write anything back. Nothing is running now: the server starts when
        another app launches it, and stops when that app closes.
      </p>
      {result.droppedMemories > 0 && (
        <p className="muted">
          {result.droppedMemories} of your memories were left out because they are not
          sample records.
        </p>
      )}
      {result.skippedVault && (
        <p className="muted">
          The knowledge vault was left out because it is not the sample one.
        </p>
      )}
      <p>Add this to another app&apos;s MCP configuration:</p>
      <pre>{status.endpoint.clientConfig}</pre>
      <p className="muted">
        You can find this again in Control Center &rarr; MCP servers.
      </p>
    </Modal>
  );
}

